### ISSUE TITLE
strings with the comment syntax in them breaks the parser

### ISSUE THREAD

**Issue by FredrikHson** [kimkulling/openddl-parser#30]
this is a part of a file that i exported from blender.
blender apparently uses //f/ for f:\ so the parser thinks its a comment with the closing "} 
making it unable to parse the file.
[kitty.txt](https://github.com/kimkulling/openddl-parser/files/50553/kitty.txt)

**Comment by kimkulling** [comment]
Interesting point, thank you very much for the report. I am currently working on a fix.

**Comment by kimkulling** [comment]
Is this related to the OpenGEX format?

**Comment by FredrikHson** [comment]
its a general issue but yes came up with writing a opengex importer for my game engine

**Comment by kimkulling** [comment]
Shall be fixed now.
