### ISSUE TITLE
Failed to parse LightObject

### ISSUE THREAD

**Issue by henrya2** [kimkulling/openddl-parser#38]
> 
> LightObject $light1 (type = "point")		// Lamp
> {
> 	Color (attrib = "light") {float[3] {{1.0, 1.0, 1.0}}}
> 
> 	Atten (curve = "inverse_square")
> 	{
> 		Param (attrib = "scale") {float {5.47722400800463}}
> 	}
> }

#39

**Comment by henrya2** [comment]
#39

**Comment by kimkulling** [comment]
Closed by https://github.com/kimkulling/openddl-parser/pull/39
