### ISSUE TITLE
DataArrayList::size() returns wrong size

### ISSUE THREAD

**Issue by paul-z** [kimkulling/openddl-parser#41]
If the linked list has 1 element, m_next is null, and return 0 instead of 1.
Also time complexity should be reduced to O(1) by keeping a size attribute for each list...

**Comment by kimkulling** [comment]
Thanks a lot for the issue report. Should be fixed now.

**Comment by kimkulling** [comment]
Closed by e1d898adbc772aef39b3bc50dd76058565f5309a
