### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [kimkulling/openddl-parser#47]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
* [OpenDDLParser::clear](https://github.com/kimkulling/openddl-parser/blob/fdd985d651c4a30e842143007f9be7c267093944/code/OpenDDLParser.cpp#L194 "OpenDDLParser::clear function")
* [ValueTest::TearDown](https://github.com/kimkulling/openddl-parser/blob/fdd985d651c4a30e842143007f9be7c267093944/test/ValueTest.cpp#L37 "ValueTest::TearDown function")
* [Value](https://github.com/kimkulling/openddl-parser/blob/fdd985d651c4a30e842143007f9be7c267093944/code/Value.cpp#L112 "Destructor for Value")

**Comment by kimkulling** [comment]
Fixed!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/kimkulling/openddl-parser/commit/7619f42e5de8056ec68022b862f1b5546a8af72c "Deletion of a few checks").
